// This file is auto-generated by the legal docs build process
// Import legal document URLs from package.json
import legalPackage from '../../legal/package.json';

export const TERMS_URL = legalPackage.latestTerms;
export const PRIVACY_URL = legalPackage.latestPrivacy;
export const TERMS_DATE = legalPackage.latestTermsDate;
export const PRIVACY_DATE = legalPackage.latestPrivacyDate;
